"""
E2E Training — A1 + Domain Adversarial Loss (A1_e2e_dadv)
===========================================================

Fully end-to-end training: AV-HuBERT fully unfrozen + A1 causal head
with BOTH label-adversarial and domain-adversarial losses.

Architecture:
  AV-HuBERT (all layers unfrozen, lr_encoder=1e-6)
       ↓  video_feats [B, T, 1024],  audio_feats [B, T, 1024]
  AVH_Causal_Ablation (use_adv=True, use_sg=False, use_domain=True)
       ↓
  Z_c  →  full_head(Z_c + Z_s) [primary cls]
           causal_head(Z_c)     [secondary, used at eval]
  Z_s  →  adv_head(GRL(Z_s))   [label adversarial]
           domain_head(GRL(Z_s)) [domain adversarial]

Training data:
  AV1M:  ALL available preprocessed clips via comprehensive CSV
         (generated by generate_e2e_csv.py — ~63k clips vs 8k before)
  FAVC real (domain=1):  val split real-only clips, no task labels

Usage:
  python train_e2e_a1_dadv.py --config_path configs/A1_e2e_dadv.yaml
"""

import argparse
import math
import os
import random
import sys

import numpy as np
import torch
import yaml
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import StratifiedKFold, cross_val_predict
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from torch.utils.data import DataLoader, ConcatDataset, Dataset, Subset
import lightning as L
from lightning.pytorch.callbacks import EarlyStopping, ModelCheckpoint
from lightning.pytorch.loggers import CSVLogger

sys.path.insert(0, os.path.dirname(__file__))
from avhubert_wrapper import AVHubertWrapper
from mlp_causal_ablation import AVH_Causal_Ablation
from datasets_e2e import (
    AV1M_E2E_FullPathDataset,
    FakeAVCeleb_E2E_Dataset,
    e2e_collate_fn,
)


# ── Reproducibility ───────────────────────────────────────────────────────────

def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


# ── Domain label wrapper ──────────────────────────────────────────────────────

class DomainLabeledDataset(Dataset):
    """Adds a domain label to any base dataset returning (v, a, cls, path)."""

    def __init__(self, dataset, domain_label: int, cls_label_override=None):
        self.dataset            = dataset
        self.domain_label       = domain_label
        self.cls_label_override = cls_label_override

    def __len__(self):
        return len(self.dataset)

    def __getitem__(self, idx):
        video, audio, cls_label, path = self.dataset[idx]
        if self.cls_label_override is not None:
            cls_label = self.cls_label_override
        return video, audio, cls_label, self.domain_label, path


# ── E2E Lightning Module ──────────────────────────────────────────────────────

class E2EModelA1DADV(L.LightningModule):
    """
    End-to-end model: AVHubertWrapper (fully unfrozen) + AVH_Causal_Ablation
    with label-adversarial and domain-adversarial losses.

    Training batch: (video [B,T,1,H,W], audio [B,T,104],
                     cls_labels [B], domain_labels [B], paths)
    Validation batch: same format (domain_labels all 0 for AV1M val)
    """

    def __init__(self, config: dict):
        super().__init__()
        self.save_hyperparameters({"config": config})
        self.config = config
        hp = config.get("model_hparams", {})

        # ── Build AV-HuBERT encoder (fully unfrozen) ─────────────────────────
        self.encoder = AVHubertWrapper(
            ckpt_path         = hp["avhubert_ckpt"],
            avhubert_root     = hp.get("avhubert_root", ""),
            n_unfreeze_layers = int(hp.get("n_unfreeze_layers", -1)),
        )

        # ── Build A1 head (use_adv + use_domain) ─────────────────────────────
        self.head = AVH_Causal_Ablation(config=config)

        self._val_scores: list = []
        self._val_labels: list = []
        self.domain_probe_loader = None

    # ── Two-group optimizer ───────────────────────────────────────────────────

    def configure_optimizers(self):
        hp = self.config.get("model_hparams", {})
        lr_encoder   = float(hp.get("lr_encoder",   1e-6))
        lr_head      = float(hp.get("lr",           1e-4))
        weight_decay = float(hp.get("weight_decay", 1e-4))

        encoder_params = [p for p in self.encoder.parameters() if p.requires_grad]
        head_params    = list(self.head.parameters())

        optimizer = torch.optim.AdamW([
            {"params": encoder_params, "lr": lr_encoder},
            {"params": head_params,    "lr": lr_head},
        ], weight_decay=weight_decay)

        scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
            optimizer, mode="max", patience=5, factor=0.5, verbose=True
        )
        return {
            "optimizer": optimizer,
            "lr_scheduler": {
                "scheduler": scheduler,
                "monitor":   "val_auc_causal",
                "interval":  "epoch",
            },
        }

    # ── Shared encoding step ──────────────────────────────────────────────────

    def _encode_batch(self, batch):
        """Run raw video/audio through AV-HuBERT → (feats, feats, cls, domain)."""
        video_raw, audio_raw, cls_labels, domain_labels, paths = batch
        video_feats, audio_feats = self.encoder(video_raw, audio_raw)
        return video_feats, audio_feats, cls_labels, domain_labels, paths

    # ── Training step ─────────────────────────────────────────────────────────

    def training_step(self, batch, batch_idx):
        if batch is None:
            return None

        # Progressive DANN alpha: ramp grl_domain_alpha from 0 → max over training
        hp = self.config.get("model_hparams", {})
        if hp.get("dann_progressive", False) and hasattr(self.head, "grl_domain"):
            gamma     = float(hp.get("dann_gamma", 10.0))
            alpha_max = float(hp.get("grl_domain_alpha", 5.0))
            p         = self.global_step / max(self.trainer.estimated_stepping_batches, 1)
            alpha     = alpha_max * (2.0 / (1.0 + math.exp(-gamma * p)) - 1.0)
            self.head.grl_domain.alpha = alpha

        video_feats, audio_feats, cls_labels, domain_labels, paths = \
            self._encode_batch(batch)

        feat_batch = (video_feats, audio_feats, cls_labels, domain_labels, paths)

        # Delegate to AVH_Causal_Ablation.training_step via trainer patching
        # so that self.log() calls from the head are routed through this trainer.
        self.head._trainer        = self._trainer
        self.head._current_fx_name = "training_step"
        try:
            loss = self.head.training_step(feat_batch, batch_idx)
        finally:
            self.head._trainer        = None
            self.head._current_fx_name = None
        return loss

    def on_train_batch_end(self, outputs, batch, batch_idx):
        if self.global_step % 500 == 0:
            loss_val = outputs["loss"].item() if isinstance(outputs, dict) and "loss" in outputs else float(outputs) if outputs is not None else float("nan")
            total = self.trainer.estimated_stepping_batches
            print(f"[Step {self.global_step:06d}/{int(total)}] loss={loss_val:.4f}", flush=True)

    # ── Validation step ───────────────────────────────────────────────────────

    def validation_step(self, batch, batch_idx):
        if batch is None:
            return
        video_feats, audio_feats, cls_labels, _domain_labels, _paths = \
            self._encode_batch(batch)
        scores = self.head(video_feats, audio_feats, mode="causal")
        self._val_scores.append(scores.detach().cpu())
        self._val_labels.append(cls_labels.cpu())

    # ── Domain probe ──────────────────────────────────────────────────────────

    @torch.no_grad()
    def _run_domain_probe(self):
        """
        Logistic-regression domain probe on Z_c (causal_repr) and Z_s (spurious_repr).

        Reports:
          domain_auc_zc_raw      — raw Z_c logistic probe (want LOW, <0.65)
          domain_auc_zc_centered — after per-domain mean subtraction (covariance residual)
          domain_auc_zs_raw      — raw Z_s logistic probe (want HIGH, >0.80 — domain pull working)
        """
        self.eval()
        zc_list, zs_list, dom_list = [], [], []
        device = next(self.parameters()).device

        for batch in self.domain_probe_loader:
            if batch is None:
                continue
            video_raw, audio_raw, _, domain_labels, _ = batch
            video_raw = video_raw.to(device)
            audio_raw = audio_raw.to(device)
            video_feats, audio_feats = self.encoder(video_raw, audio_raw)
            causal_repr, spurious_repr, _ = self.head._encode(video_feats, audio_feats)
            zc_list.append(causal_repr.mean(1).cpu().numpy())
            zs_list.append(spurious_repr.mean(1).cpu().numpy())
            dom_list.extend(domain_labels.tolist())

        zc_all  = np.concatenate(zc_list)
        zs_all  = np.concatenate(zs_list)
        dom_all = np.array(dom_list)

        def _probe(X, y, n_folds=5):
            pipe = make_pipeline(
                StandardScaler(),
                LogisticRegression(max_iter=500, C=1.0, solver="lbfgs"),
            )
            skf   = StratifiedKFold(n_splits=n_folds, shuffle=True, random_state=0)
            probs = cross_val_predict(pipe, X, y, cv=skf, method="predict_proba")[:, 1]
            try:
                return roc_auc_score(y, probs)
            except Exception:
                return 0.5

        auc_zc_raw = _probe(zc_all, dom_all)
        auc_zs_raw = _probe(zs_all, dom_all)

        # Centered Z_c: remove per-domain mean → test covariance residual
        zc_centered = zc_all.copy()
        for d in [0, 1]:
            idx_d = (dom_all == d)
            if idx_d.sum() > 1:
                zc_centered[idx_d] -= zc_centered[idx_d].mean(0)
        auc_zc_centered = _probe(zc_centered, dom_all)

        self.train()
        return auc_zc_raw, auc_zc_centered, auc_zs_raw

    def on_validation_epoch_end(self):
        if not self._val_scores:
            return
        scores = torch.cat(self._val_scores).numpy()
        labels = torch.cat(self._val_labels).numpy()
        self._val_scores.clear()
        self._val_labels.clear()
        # Only score on valid labels (cls >= 0)
        mask = labels >= 0
        if mask.sum() < 2:
            return
        try:
            auc = roc_auc_score(labels[mask], scores[mask])
        except Exception:
            auc = 0.5
        self.log("val_auc_causal", auc, prog_bar=True)

        if self.domain_probe_loader is not None:
            auc_zc_raw, auc_zc_centered, auc_zs_raw = self._run_domain_probe()
            ep = self.current_epoch
            print(
                f"\n[Epoch {ep:02d}] val_auc_causal={auc:.4f}"
                f"  |  domain probe:"
                f"  Z_c raw={auc_zc_raw:.4f} (want <0.65)"
                f"  Z_c centered={auc_zc_centered:.4f}"
                f"  Z_s raw={auc_zs_raw:.4f} (want >0.80)",
                flush=True,
            )
            self.log("domain_auc_zc_raw",      auc_zc_raw,      on_epoch=True, prog_bar=False)
            self.log("domain_auc_zc_centered", auc_zc_centered, on_epoch=True, prog_bar=False)
            self.log("domain_auc_zs_raw",      auc_zs_raw,      on_epoch=True, prog_bar=False)
        else:
            print(f"\n[Epoch {self.current_epoch:02d}] val_auc_causal={auc:.4f}", flush=True)


# ── Data loading ──────────────────────────────────────────────────────────────

def load_data(config: dict):
    dp          = config["data_paths"]
    train_csv   = dp["e2e_train_csv"]
    val_csv     = dp["e2e_val_csv"]
    favc_root   = dp.get("favc_raw_root", "")
    hp          = config.get("model_hparams", {})
    max_frames  = int(hp.get("max_frames", 150))
    batch_size  = int(config.get("batch_size", 4))
    num_workers = int(config.get("num_workers", 4))

    # ── AV1M train (domain=0, with task labels) ───────────────────────────────
    av1m_base  = AV1M_E2E_FullPathDataset(train_csv, max_frames=max_frames)
    av1m_train = DomainLabeledDataset(av1m_base, domain_label=0)
    print(f"[load_data] AV1M train clips: {len(av1m_base)}", flush=True)

    # ── FAVC real (domain=1, no task labels) ──────────────────────────────────
    favc_oversample = int(config.get("favc_oversample", 1))
    if favc_root and os.path.isdir(favc_root):
        favc_ds = FakeAVCeleb_E2E_Dataset(
            favc_root, max_frames=max_frames, real_only=True
        )
        favc_dom = DomainLabeledDataset(favc_ds, domain_label=1, cls_label_override=-1)
        print(f"[load_data] FAVC real domain clips: {len(favc_ds)}", flush=True)
        if favc_oversample > 1:
            favc_dom = ConcatDataset([favc_dom] * favc_oversample)
            print(f"[load_data] FAVC oversampled {favc_oversample}× → {len(favc_dom)} clips", flush=True)
        train_ds = ConcatDataset([av1m_train, favc_dom])
    else:
        print("[load_data] WARNING: favc_raw_root not found — "
              "training without domain signal.", flush=True)
        train_ds = av1m_train

    # ── AV1M val (domain=0, task labels present) ─────────────────────────────
    av1m_val_base = AV1M_E2E_FullPathDataset(val_csv, max_frames=max_frames)
    val_ds        = DomainLabeledDataset(av1m_val_base, domain_label=0)
    print(f"[load_data] AV1M val clips: {len(av1m_val_base)}", flush=True)

    train_loader = DataLoader(
        train_ds, batch_size=batch_size, shuffle=True,
        num_workers=num_workers, collate_fn=e2e_collate_fn,
        pin_memory=True, drop_last=True, persistent_workers=True,
    )
    val_loader = DataLoader(
        val_ds, batch_size=batch_size, shuffle=False,
        num_workers=num_workers, collate_fn=e2e_collate_fn,
        pin_memory=True, persistent_workers=True,
    )

    # ── Domain probe loader (200 AV1M val + 200 FAVC, no augmentation) ────────
    # Probes Z_c / Z_s for domain separability every epoch.
    # Uses same real_only=True as the training FAVC split.
    n_probe   = 200
    rng_probe = np.random.default_rng(0)
    av1m_probe_base = AV1M_E2E_FullPathDataset(val_csv, max_frames=max_frames)
    av1m_probe = DomainLabeledDataset(
        Subset(av1m_probe_base, list(range(min(n_probe, len(av1m_probe_base))))),
        domain_label=0,
    )
    domain_probe_loader = None
    if favc_root and os.path.isdir(favc_root):
        favc_probe_base = FakeAVCeleb_E2E_Dataset(
            favc_root, max_frames=max_frames, real_only=True
        )
        favc_probe_idx = rng_probe.choice(
            len(favc_probe_base), size=min(n_probe, len(favc_probe_base)), replace=False
        ).tolist()
        favc_probe = DomainLabeledDataset(
            Subset(favc_probe_base, favc_probe_idx),
            domain_label=1, cls_label_override=-1,
        )
        probe_ds = ConcatDataset([av1m_probe, favc_probe])
        domain_probe_loader = DataLoader(
            probe_ds, batch_size=8, shuffle=False,
            num_workers=2, collate_fn=e2e_collate_fn,
        )
        print(
            f"[load_data] Domain probe loader: {len(av1m_probe)} AV1M + "
            f"{len(favc_probe)} FAVC real (no augmentation)", flush=True
        )

    return train_loader, val_loader, domain_probe_loader


# ── Entry point ───────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--config_path", required=True)
    args = parser.parse_args()

    with open(args.config_path) as f:
        config = yaml.safe_load(f)

    set_seed(config.get("seed", 43))
    torch.set_float32_matmul_precision("medium")  # enable Tensor Core TF32

    train_loader, val_loader, domain_probe_loader = load_data(config)
    model = E2EModelA1DADV(config=config)
    model.domain_probe_loader = domain_probe_loader

    # ── Callbacks ─────────────────────────────────────────────────────────────
    cb_cfg   = config.get("callbacks", {})
    ckpt_cfg = cb_cfg.get("ckpt_args", {})
    log_cfg  = cb_cfg.get("logger", {})

    logger = CSVLogger(
        save_dir = log_cfg.get("log_path", "outputs_A1_e2e_dadv/logs"),
        name     = "",
    )
    ckpt_cb = ModelCheckpoint(
        dirpath   = ckpt_cfg.get("ckpt_dir",  "outputs_A1_e2e_dadv/ckpts"),
        filename  = "model-{epoch:02d}-{val_auc_causal:.4f}",
        monitor   = ckpt_cfg.get("metric", "val_auc_causal"),
        mode      = ckpt_cfg.get("mode",   "max"),
        save_top_k = 1,
        save_last  = True,
    )
    es_cfg = config.get("early_stopping", {})
    es_cb  = EarlyStopping(
        monitor  = es_cfg.get("metric",   "val_auc_causal"),
        mode     = es_cfg.get("mode",     "max"),
        patience = int(es_cfg.get("patience", 10)),
        verbose  = True,
    )

    # ── Trainer ───────────────────────────────────────────────────────────────
    accum  = int(config.get("accumulate_grad_batches", 8))
    clip   = float(config.get("gradient_clip_val", 1.0))
    prec   = config.get("precision", "16-mixed")

    trainer = L.Trainer(
        max_epochs               = int(config.get("epochs", 30)),
        accelerator              = "gpu",
        devices                  = 1,
        precision                = prec,
        accumulate_grad_batches  = accum,
        gradient_clip_val        = clip,
        callbacks                = [ckpt_cb, es_cb],
        logger                   = logger,
        log_every_n_steps        = 10,
        enable_progress_bar      = True,
    )

    trainer.fit(model, train_loader, val_loader)
    print(f"Best checkpoint: {ckpt_cb.best_model_path}", flush=True)


if __name__ == "__main__":
    main()
