ablation_id: "A2_favc_seed45"
ablation:
  use_adv:    true
  use_sg:     true
  use_domain: false

data_info:
  name: "FAVC"
  root_path: "/data/projects/punim2637/nnliang/AVH-Align/data/favc_features"
  csv_root_path: "/data/projects/punim2637/nnliang/AVH-Align/avh_sup/csv_metadata/favc"
  apply_l2: true

model_hparams:
  feat_dim:  1024
  proj_dim:  512
  lambda_orth:    0.5
  lambda_adv:    10.0
  lambda_domain:  0.0
  grl_alpha:      5.0
  grl_domain_alpha: 1.0
  lr: 1.0e-3

callbacks:
  logger:
    log_path: "/data/projects/punim2637/nnliang/AVH-Align/avh_sup/outputs_A2_favc_seed45/logs"
    name: "csv"
  ckpt_args:
    ckpt_dir: "/data/projects/punim2637/nnliang/AVH-Align/avh_sup/outputs_A2_favc_seed45/ckpts"
    metric: "val_auc_causal"
    mode: "max"

epochs: 50
seed: 45

early_stopping:
  metric:   "val_auc_causal"
  mode:     "max"
  patience: 20
